version: '3'
services:
    words-db:
        image: mysql:8
        command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1
        container_name: words-db
        networks:
            - api-network
        ports:
            - '33069:3306'
        volumes:
            - ./data_dir:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: tiger
            MYSQL_DATABASE: words
            MYSQL_USER: gundo
            MYSQL_PASSWORD: tigers

volumes:
    elasticsearch-data:
        driver: local

networks:
    api-network:
        driver: bridge
